### ISSUE TITLE
Invalid Property Error when using an empty base dir

### ISSUE THREAD

**Issue by GritBear** [Automattic/juice#147] opened 2015-07-31 08:22 UTC
I don't need to use relative path and all my codes are in jade (so no dir for htmls). 

The processHtml outputs well but it always throw the following error:

error: Property word-break: break-word at ..\..\views\-html-#58 is invalid: Expected (normal | keep-all | break-all) but
 found 'break-word'.
error: Property word-break: bold at ..\..\views\-html-#278 is invalid: Expected (normal | keep-all | break-all) but foun
d 'bold'.

Where " ..\..\views\" is the path I set for baseDir. If I leave baseDir empty it will throw the same error in console with path = undefined.

I don't quite understand this as "..\..\views\-html-" is no a file.

**Comment by jrit** [comment] 2015-08-01 22:50
Looks like your CSS is in fact invalid. Valid properties for word-break should be listed here https://developer.mozilla.org/en-US/docs/Web/CSS/word-break - `bold` and `break-word` don't appear as valid values.

**Comment by GritBear** [comment] 2015-08-04 05:13
hi jrit,

I have no idea what css this error is referring to. I don't have any css link in the html nor in the base dir (base dir is null). I don't have a break-word in the html either.

browser/juice both do not return any error.

**Comment by jrit** [comment] 2015-08-04 13:56
Can you post an isolated case where this can be reproduced?

**Comment by jrit** [comment] 2015-09-24 13:42
Closing as there hasn't been a reproducible case provided, but it seems to me there is an issue in the CSS itself from the error.

**Closed by jrit** 2015-09-24 13:42 UTC
